APCA_API_BASE_URL='https://paper-api.alpaca.markets'
APCA_API_KEY_ID='PKTTXBWKZZXVMP5JXVPO'
APCA_API_SECRET_KEY='0CgYbN2tp1AtWyjCrgysWvEviMF1g4tw31wA2YXZ'
AV_API_KEY_ID='F1QACIJR7DUPCA2T'
OPEN_TIME = 570
CLOSE_TIME = 960